name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  release_docker_amd64:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - name: Init
      uses: actions/checkout@v3
    - name: Setup
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Run
      run: |
        docker build -t ilaurens/filestash:latest-amd64 ./docker/
        docker push ilaurens/filestash:latest-amd64

  release_docker:
    needs: [ release_docker_amd64 ]
    runs-on: ubuntu-latest
    steps:
    - name: Init
      uses: actions/checkout@v3
    - name: Setup
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Run
      run: |
        docker manifest create ilaurens/filestash:latest \
          --amend ilaurens/filestash:latest-amd64
        docker manifest push ilaurens/filestash:latest
